### ISSUE TITLE
Jira CLI in Go with TDD to automate some recurring Jira tasks

### ISSUE THREAD

**Issue by sebastian-sommerfeld-io** [sebastian-sommerfeld-io/jiracli#1]
There are two perspectives to look at this story:

1. As a Jira administrator I want to automate recurring tasks using the [Jira REST API](https://developer.atlassian.com/server/jira/platform/rest-apis).
2. As a developer and DevOps engineer I want to follow a TDD approach. Additionally I want to learn more about [Go](https://go.dev) so this is the language/evironment of choise to implement the app.

### Acceptance Criteria
- [ ] ...
- [ ] ...
- [ ] ...

### Implementation Tasks
- [x] sebastian-sommerfeld-io/jiracli#28
- [x] A new repository `jira-cli` or `jira-ops-cli` is present.
- [x] Derive a README.adoc from story
- [x] This ticket and all sub-tickets are moved to the new repository. All links are working.
- [x] Bind tickets to project https://github.com/users/sebastian-sommerfeld-io/projects/2
- [x] The basic repository configuration is done by Terraform (https://github.com/sebastian-sommerfeld-io/configs)
    - [x] Issue labels contain "19+1" label
- [x] Learn about CLI applications in Go (https://go.dev/solutions/clis)
- [ ] Learn about how to structure the repository (https://github.com/golang-standards/project-layout, https://github.com/bnkamalesh/goapp, https://levelup.gitconnected.com/structuring-your-go-applications-aka-staying-sane-with-go-projects-7d5bb38ff6af)
- [x] sebastian-sommerfeld-io/jiracli#17
- [x] sebastian-sommerfeld-io/jiracli#3
- [x] sebastian-sommerfeld-io/jiracli#4
- [x] sebastian-sommerfeld-io/jiracli#43
- [x] sebastian-sommerfeld-io/jiracli#5
- [x] sebastian-sommerfeld-io/jiracli#6
- [x] sebastian-sommerfeld-io/jiracli#9
- [ ] sebastian-sommerfeld-io/tron#6
- [x] sebastian-sommerfeld-io/jiracli#8
- [ ] sebastian-sommerfeld-io/tron#2
- [x] sebastian-sommerfeld-io/jiracli#14
- [x] sebastian-sommerfeld-io/jiracli#16
- [x] sebastian-sommerfeld-io/jiracli#20
- [x] sebastian-sommerfeld-io/jiracli#23
- [x] sebastian-sommerfeld-io/jiracli#60

#### CLI tasks to implement (add more tasks with dedicated user stories)
- [x] sebastian-sommerfeld-io/jiracli#10
- [x] sebastian-sommerfeld-io/jiracli#11
- [x] sebastian-sommerfeld-io/jiracli#12
- [x] sebastian-sommerfeld-io/jiracli#15
- [x] sebastian-sommerfeld-io/jiracli#26
- [x] sebastian-sommerfeld-io/jiracli#24
    - [x] sebastian-sommerfeld-io/jiracli#45
- [x] sebastian-sommerfeld-io/jiracli#39
- [x] sebastian-sommerfeld-io/jiracli#49

**Comment by sebastian-sommerfeld-io** [comment]
### Ideas / Futures
- Bundle the app in a Docker container. 
- Use Docker Compose to startup a Jira instance and afterwards the app
- Run some automated tests against the Jira instance
- Shutdown everything and clean up (Jira for startup should be the same state as before the tests)

**Comment by sebastian-sommerfeld-io** [comment]
### Follow Up User Story
As a project maintainer I want to auto-generate docs based on the `--help` information and publish these docs on www.sommerfeld.io.

Either generate Antora docs or generate something similar to https://cli.github.com/manual.

### Acceptance Criterla 
- [ ] To ...
- [ ] Be ...
- [ ] Defined ...

**Comment by sebastian-sommerfeld-io** [comment]
### Source Code Design
- `src/main/go/commands` = CLI options
- `src/main/go/services` = Service Layer between CLI options and real remote services
- `src/main/go/dao` = Consume remote services (better name??) ... maybe this should be named services?
